apiVersion: v1
kind: Secret
metadata:
  name: cuisineensemble-secrets
type: Opaque
stringData:
  database-url: postgresql+psycopg2://cuisine_user:cuisine_password@postgres:5432/cuisineensemble
  secret-key: change-this-secret-key
